name: Node CI
on:
  push:
    branches:
      - 'tushar'

jobs:
  dev-build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/tushar'
    steps:
      - uses: actions/checkout@v3
        with:
          ref: tushar

      - name: Prepare Deployment Directory
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo chown -R ubuntu:ubuntu /home/ubuntu/bankmanagement/
            sudo chmod -R 775 /home/ubuntu/bankmanagement/
            sudo rm -rf /home/ubuntu/bankmanagement/
            sudo mkdir /home/ubuntu/bankmanagement/
            sudo chown -R ubuntu:ubuntu /home/ubuntu/bankmanagement/

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          ARGS: '-avz --no-perms --no-group --exclude=/dist/ --exclude=/node_modules/ --exclude=.git/ --exclude=/__mock__/ --exclude=/__test__/ --exclude=/docker/ --exclude=/dockerfiles/'
          SOURCE: './'
          REMOTE_HOST: ${{ secrets.EC2_HOST }}
          REMOTE_USER: ${{ secrets.EC2_USER }}
          TARGET: '/home/ubuntu/bankmanagement/'

      - name: Build and Restart Application
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/bankmanagement/
            sudo pm2 delete all || true
            mvn clean package
            sudo pm2 start java -- -jar target/banking-0.0.1-SNAPSHOT.jar --name bankmanagement